project:
  type: book
  output-dir: docs
  resources:
    - .nojekyll

book:
  title: "The Backbone of Impact Evaluation Methods"
  subtitle: "Back to Basics"
  author: "Augusto Cerqua"
  date: "2026-06-23"
  cover-image: images/book_cover_v2.png
  site-url: "https://augustocerqua.github.io/Back-to-basics-book/"
  repo-url: "https://github.com/augustocerqua/Back-to-basics-book"
  repo-actions: [issue]
  sharing: [twitter, linkedin]
  page-footer:
    left: "© Augusto Cerqua"
    right: "Built with Quarto"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/01-why-impact-evaluation.qmd
        - chapters/02-potential-outcomes.qmd
        - chapters/03-causal-parameters.qmd
    - part: "Control-based Designs"
      chapters:
        - chapters/04-randomized-experiments.qmd
        - chapters/05-selection-on-observables.qmd
        - chapters/06-difference-in-differences.qmd
        - chapters/07-event-studies.qmd
        - chapters/08-instrumental-variables.qmd
        - chapters/09-regression-discontinuity.qmd
        - chapters/10-synthetic-control.qmd
    - part: "Other topics"
      chapters:
        - chapters/11-forecast-based-designs.qmd
        - chapters/12-heterogeneous_treatment_effects.qmd
        - chapters/13-spillover_effects.qmd
        - chapters/14-continuous_treatment.qmd
        - chapters/15-miscellanea.qmd
  appendices:
    - chapters/appendix-technical-language.qmd
    - chapters/references.qmd

bibliography: references/references.bib
# csl: references/american-economic-association.csl

website:
  google-analytics: "G-X0W71GV1V8"

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles/styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: false
    code-tools: false
    fig-cap-location: bottom
    tbl-cap-location: top

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
