project:
  type: book
  output-dir: docs

book:
  title: "The Backbone of Impact Evaluation Methods"
  subtitle: "Back to Basics"
  author: "Augusto Cerqua"
  date: today
  cover-image: images/book_cover.png
  site-url: "https://augustocerqua.github.io/backbone-impact-evaluation/"
  repo-url: "https://github.com/augustocerqua/backbone-impact-evaluation"
  repo-actions: [edit, issue]
  downloads: [pdf, epub]
  sharing: [twitter, linkedin]
  page-footer:
    left: "© Augusto Cerqua"
    right: "Built with Quarto"
  chapters:
    - index.qmd
    - part: "Foundations"
      chapters:
        - chapters/01-why-impact-evaluation.qmd
        - chapters/02-potential-outcomes.qmd
        - chapters/03-causal-parameters.qmd
    - part: "Control-based Designs"
      chapters:
        - chapters/04-randomized-experiments.qmd
        - chapters/05-selection-on-observables.qmd
        - chapters/06-difference-in-differences.qmd
        - chapters/07-event-studies.qmd
        - chapters/08-regression-discontinuity.qmd
        - chapters/09-instrumental-variables.qmd
        - chapters/10-synthetic-control.qmd
    - part: "Other topics"
      chapters:
        - chapters/11-forecast-based-designs.qmd
        - chapters/12-heterogeneous_treatment_effects.qmd
        - chapters/13-spillover_effects.qmd
        - chapters/14-continuous_treatment.qmd
    - chapters/references.qmd

bibliography: references/references.bib
# csl: references/american-economic-association.csl

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css: styles/styles.css
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    fig-cap-location: bottom
    tbl-cap-location: top
pdf:
  documentclass: scrreprt
  toc: true
  number-sections: true
  colorlinks: true
  include-in-header:
  - cover.tex
  - text: |
      \usepackage{caption}
      \captionsetup[figure]{font=small}
  epub:
    toc: true

execute:
  freeze: auto
  echo: true
  warning: false
  message: false
